In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

from flask import render_template

In [5]:
num_squares = 400
side_length = int(np.sqrt(num_squares))

board = np.random.binomial(1, .2, size=400).reshape(20,20)

In [20]:
strng = ''
test = 'abcd'

def func(test_string):
    temp = ''
    for i in test_string:
        temp +=f'{i}\n'
    print(temp)
    return

In [31]:
for i in range(1, len(board)+1):
    print(f'LINE{i}:{board[i]}')

LINE1:[0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
LINE2:[0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1]
LINE3:[0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0]
LINE4:[1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0]
LINE5:[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
LINE6:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
LINE7:[0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0]
LINE8:[0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0]
LINE9:[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0]
LINE10:[1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
LINE11:[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
LINE12:[1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1]
LINE13:[0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 0 0 1]
LINE14:[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
LINE15:[0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
LINE16:[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1]
LINE17:[0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1]
LINE18:[0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0]
LINE19:[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]


IndexError: index 20 is out of bounds for axis 0 with size 20

In [6]:
for i in board:
    print(str(i))

[1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1 0 0]
[0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1]
[0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0]
[1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0]
[0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0]
[0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0]
[1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0]
[1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1]
[0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 1 0 0 0 1]
[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1]
[0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1]
[0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]


In [9]:
# board = np.random.randint(1, size =400).reshape(20,20)
board

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1,

In [235]:
def check(x,y):
    if(board[x][y]):
        return "Boom! Game Over."
    
    return "Safe!" 


def flag():
    x = int(request.args.get('x'))
    y = int(request.args.get('y'))
    
    if(board[x][y]):
        return "That's a bomb alright!"
    
    return "Nope! Game Over." 


def solution():
    return board



def mine_counts(x,y):
    return

# def kernel(x,y):
#     lower_limit_x = x-2
#     lower_limit_y = y-2
#     upper_limit_x = x+3
#     upper_limit_y = y+3
    
#     if lower_limit_x < 0:
#         lower_limit_x == 0
#     if lower_limit_y < 0:
#         lower_limit_y == 0
# #     if upper_limit_x > 0:
# #         upper_limit_x == 0
# #     if lower_limit_x < 0:
# #         lower_limit_x == 0
    
#     sub = board[lower_limit_x:upper_limit_x,lower_limit_y: upper_limit_y]
    
#     return(sub)


def kernel(x,y):
    the_kernel = np.zeros((5,5))
    
    if x-2 <0:
        x_start = -1*(x-2)
        top = x-2+x_start
    else:
        x_start = 0
        top = x-2
    if y-2 <0:
        y_start = -1*(y-2)
        left = y-2+y_start
    else:
        y_start = 0
        left = y-2
    
    
    
    
#     the_kernel[x_start:the_kernel.shape[0]-1 , y_start:the_kernel.shape[1]-1] = board[left:x+3,top:x+3]
    print(x_start)
    print(y_start)
    print(left)
    print(top)
        
    return(board[left:x+3,top:x+3])#x_start, left, y_start, top)



In [236]:
kernel(1,1)
# board[0-2:0+3,0-2:0+3].shape

1
1
0
0


array([[ 1,  3,  6, 16],
       [ 5,  9,  2, 13],
       [ 3,  0,  9, 13],
       [14, 12,  2, 12]])

In [165]:
board

array([[ 1,  3,  6, 16, 16, 12,  7,  3, 12, 10],
       [ 5,  9,  2, 13, 14,  4, 19,  4,  6, 13],
       [ 3,  0,  9, 13,  3,  9, 10,  5, 13,  6],
       [14, 12,  2, 12,  2,  1,  5,  0, 12,  9],
       [ 5, 19,  2, 15,  9, 19, 17, 19,  7,  8],
       [16, 18,  1,  9, 13, 11,  5, 19, 12, 13],
       [ 8, 14,  0, 11, 15, 10, 16, 11,  2, 16],
       [ 4,  5, 14, 19, 13, 11,  6, 13,  6, 10],
       [ 8, 13, 17, 15, 16, 11,  0,  5, 19,  2],
       [10,  2,  6,  4,  8, 17,  3,  1, 13,  7]])

In [212]:
a = np.zeros((5,5))
a[0:4,0:4] = board[6:,6:]
a.shape[0]-1

4

In [156]:
a = np.arange(9).astype('float64').reshape(3,3)
a

b = np.array([1.1,2.2,3.3,4.4]).reshape(2,2)
b

a[1:,1:] = b[0:,0:]
a

array([[0. , 1. , 2. ],
       [3. , 1.1, 2.2],
       [6. , 3.3, 4.4]])

In [83]:
bombs = np.zeros((3,3))

for i in range(1,the_kernel.shape[0]-1):
    for j in range(1,the_kernel.shape[1]-1):
        bombs[i][j] = 
bombs

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
board

array([[0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0]])

In [86]:
x = 0
y = 8
np.sum(board[x-1:x+2,y-1:y+2])

0